<div class="row-fluid sortable">		
    <div class="box span12">


        <div class="box-header well" data-original-title>
            <h2><i class="icon-user"></i>Usuários</h2>
            <div class="box-icon">
                <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
            </div>
        </div>
        
        


        <div class="box-content">
            <div class="span12" style="margin-bottom: 10px">
                <a class="btn btn-info" href="/Usuarios/adicionar/">
                    <i class="icon-edit icon-white"></i>  
                    Novo                                            
                </a>
            </div>
            
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Login</th>
                        <th>Status</th>
                        <th>Ação</th>
                    </tr>
                </thead>   
                <tbody>

                    <?php foreach ($VIEW_USUARIOS as $usuario): ?>
                        <tr>
                            <td><?php echo $usuario->getNome() ?></td>
                            <td><?php echo $usuario->getLogin() ?></td>
                            <td><?php echo $usuario->getStatus() == 1 ? 'Ativo' : 'Inativo' ?></td>

                            <td class="center">
                                <a class="btn btn-info" href="/Usuarios/editar/id/<?php echo $usuario->getId() ?>">
                                    <i class="icon-edit icon-white"></i>  
                                    Editar                                            
                                </a>
                                <a class="btn btn-danger" href="/Usuarios/excluir/id/<?php echo $usuario->getId() ?>">
                                    <i class="icon-trash icon-white"></i> 
                                    Deletar
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>


        </div>
    </div>
</div>