<form class="form-horizontal" action="/Autenticacao/Logar/" method="post">
    <fieldset>
        <div class="input-prepend" title="Usuário" data-rel="tooltip">
            <span class="add-on"><i class="icon-user"></i></span><input autofocus class="input-large span10" name="login" id="username" type="text" value="" />
        </div>
        <div class="clearfix"></div>

        <div class="input-prepend" title="senha" data-rel="tooltip">
            <span class="add-on"><i class="icon-lock"></i></span><input class="input-large span10" name="senha" id="password" type="password" value="" />
        </div>
        <div class="clearfix"></div>


        <div class="clearfix"></div>

        <p class="center span5">
            <button type="submit" class="btn btn-primary">Entrar</button>
        </p>
    </fieldset>
</form>