<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><?php echo $VIEW_HTML_TITULO_PAGINA ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">



        <?php foreach (UtilitariosHelper::getArquivosCssJs('Library/Site/css/') as $file): ?>
            <link href="<?php echo ApplicationPath::ScriptsLibrary() ?>Site/css/<?php echo $file ?>" rel="stylesheet">
        <?php endforeach; ?>

        <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->


    </head>

    <body>

        <div class="container-fluid">
            <div class="row-fluid">

                <div class="row-fluid">
                    <div class="span12 center login-header">
                        <h2>Bem-vindo ao sistema de NewsLetter</h2>
                    </div><!--/span-->
                </div><!--/row-->
                
                <div class="row-fluid">
                    <div class="well span5 center login-box">
                        <div class="alert alert-info">
                            Por favor, faça o login com seu usuário e senha.
                        </div>

                        <?php Controller::Content() ?>
                        
                        
                        <?php echo MensagemHelper::getMensagem()  ?>
                    </div><!--/span-->
                    
                </div><!--/row-->
            </div><!--/fluid-row-->

        </div><!--/.fluid-container-->




        <?php foreach (UtilitariosHelper::getArquivosCssJs('Library/Site/js') as $file): ?>
            <link href="<?php echo ApplicationPath::ScriptsLibrary() ?>Site/js<?php echo $file ?>" rel="stylesheet">
        <?php endforeach; ?>


    </body>
</html>
