<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><?php echo $VIEW_HTML_TITULO_PAGINA ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Sistema de Mail Marketing">
        <meta name="author" content="Volnei Tonato - Developer">

        <!-- Estilos -->
        <?php
            echo HtmlHelper::CssTag(ApplicationPath::ScriptsLibrary()."Bootstrap/css/bootstrap.min.css");
            echo HtmlHelper::CssTag(ApplicationPath::ScriptsLibrary()."Bootstrap/css/bootstrap-responsive.min.css");
            echo HtmlHelper::CssTag(ApplicationPath::ScriptsLibrary()."jQueryUI/css/smoothness/jquery-ui-1.9.2.custom.min.css");
        ?>

        <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        
        
        
        <!-- Scripts -->
        <?php  
            echo HtmlHelper::JavascriptTag(ApplicationPath::ScriptsLibrary() . "Bootstrap/js/bootstrap.min.js");
            echo HtmlHelper::JavascriptTag(ApplicationPath::ScriptsLibrary() . "jQueryUI/js/jquery-1.8.3.min.js");
            echo HtmlHelper::JavascriptTag(ApplicationPath::ScriptsLibrary() . "jQueryUI/js/jquery-ui-1.9.1.custom.min.js");
        ?>
    </head>

    <body>            
            <!-- topbar ends -->
            <div class="container-fluid">
                <div class="row-fluid">

                    
                    

                    <noscript>
                    <div class="alert alert-block span10">
                        <h4 class="alert-heading">Alerta!</h4>
                        <p>Você precisa ter o <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> ativado para usar este site.</p>
                    </div>
                    </noscript>

                    <div id="content" class="span10">
                        <!-- content starts -->


                        <?php echo BreadCrumbs::getBreadCrumbs() ?>

                        <?php echo MensagemHelper::getMensagem() ?>


                        <?php Controller::Content() ?>



                    </div><!--/fluid-row-->

                    <hr>

                    
                </div><!--/.fluid-container-->
            </div>

        
        <footer>
            <p class="pull-left"><?php //echo date("Y") ?></p>
            <p class="pull-right">Desenvolvido por: <a href="#">Volnei Tonato</a></p>
        </footer>
    </body>
</html>
